name: "Public Action"
description: "Trigger private workflow"

inputs:
  username:
    required: true
  image:
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger private via repository_dispatch
      shell: bash
      run: |
        echo "oli"
      # env:
      #  PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
